#--------------------
# dev:開発環境
# prd:本番環境
#--------------------

# サービス名
service: p_name

# バージョン確認
frameworkVersion: '>=2.4.0'

# カスタム設定
custom:
  # デフォルトステージ名
  defaultStage: api
  # 設定ファイル読み込み
  conf: ${file(./config/config.yml):${opt:profile}

# 基本設定
provider:
  # 利用クラウド
  name: aws
  # 言語
  runtime: python3.7
  # IAM
  profile: ${self:custom.conf}.profile}
  deploymentBucket:
    name: ${self:custom.conf}.deployBucketName}
  # 環境
  stage: ${self:custom.defaultStage}
  region: ap-northeast-1
  iamRoleStatements: ${self:custom.conf}.role}
  timeout: 30

# パッケージ情報
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

# lambda関数設定
functions:
  hello:
    name: ${self:custom.defaultStage}-hello
    handler: handler.hello
    environment: ${self:custom.conf}.env}
    description: ${self:custom.defaultStage}、hello関数
    events:
      - http:
          path: hello
          method: get

# DynamoDBの構築
resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        # キーの型を指定
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        # キーの種類を指定（ハッシュorレンジキー）
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          # プロビジョニング用設定値
          #ProvisionedThroughput:
          #ReadCapacityUnits: 1
          #WriteCapacityUnits: 1
        # オンデマンド用設定値
        BillingMode: PAY_PER_REQUEST
        # テーブル名の指定
        TableName: table_test